version: 2
jobs:
  build:
    working_directory: ~/reactive-extension-app
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
        key: reactive-extension-app-v1-{{ checksum "package-lock.json"}}
      - run: npm install
      - save_cache:
        key: reactive-extension-app-v1-{{ checksum "package-lock.json"}}
        paths:
          - "node_modules"
      - run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor --config=e2e/protractor-ci.conf.js
